BLUE_AWACS = SQUADRON:New("WIZARD", 5, "AWACS")
BLUE_AWACS:AddMissionCapability({ AUFTRAG.Type.ORBIT }, 100)
BLUE_AWACS:SetTakeoffType("Air")
BLUE_AWACS:SetFuelLowRefuel(true)
BLUE_AWACS:SetFuelLowThreshold(0.4)
BLUE_AWACS:SetTurnoverTime(30, 5)
BLUE_AWACS:SetRadio(FREQUENCIES.AWACS.wizard[1], radio.modulation.AM)

--RED_F1DDA = SQUADRON:New("F1DDA ANTIRUNWAY", 20, "F1DDA")
--RED_F1DDA:SetGrouping(2)
--RED_F1DDA:SetMissionRange(150)
--RED_F1DDA:AddMissionCapability({ AUFTRAG.Type.ESCORT }, 100)
--RED_F1DDA:AddMissionCapability({ AUFTRAG.Type.BOMBRUNWAY, AUFTRAG.Type.BOMBING }, 100)
--RED_F1DDA:SetTakeoffType("Hot")
--RED_F1DDA:SetFuelLowRefuel(false)
--RED_F1DDA:SetTurnoverTime(30, 5)
