Squadron_AWACS = SQUADRON:New("AWACS", 2, "AWACS")
Squadron_AWACS:SetCallsign(CALLSIGN.AWACS.Wizard, 1)
Squadron_AWACS:SetSkill(AI.Skill.EXCELLENT)
Squadron_AWACS:SetFuelLowThreshold(0.3)
Squadron_AWACS:SetFuelLowRefuel(true)
Squadron_AWACS:AddMissionCapability({ AUFTRAG.Type.AWACS }, 100)

Squadron_AAR = SQUADRON:New("AAR", 2, "AAR")
Squadron_AAR:SetCallsign(CALLSIGN.Tanker.Texaco, 1)
Squadron_AAR:SetSkill(AI.Skill.EXCELLENT)
Squadron_AAR:SetFuelLowThreshold(0.3)
Squadron_AAR:SetFuelLowRefuel(false)
Squadron_AAR:AddMissionCapability({ AUFTRAG.Type.TANKER }, 100)
Squadron_AAR:SetRadio(FREQUENCIES.AAR.texaco_one[1], FREQUENCIES.AAR.texaco_one[3])
Squadron_AAR:AddTacanChannel(FREQUENCIES.TACAN.texaco_one[1], FREQUENCIES.TACAN.texaco_one[1])