ZONE_SPAWN_1 = ZONE:New("SPAWN-1")
ZONE_SPAWN_2 = ZONE:New("SPAWN-2")
ZONE_SPAWN_3 = ZONE:New("SPAWN-3")
ZONE_SPAWN_4 = ZONE:New("SPAWN-4")
ZONE_SPAWN_5 = ZONE:New("SPAWN-5")
ZONE_SPAWN_6 = ZONE:New("SPAWN-6")

TEMPLATE_SU27 = "SPAWN-RED-BVR-SU27_"
TEMPLATE_MiG23 = "SPAWN-RED-BVR-M23_"
TEMPLATE_MiG29 = "SPAWN-RED-BVR-M29_"
TEMPLATE_SU30 = "SPAWN-RED-BVR-SU30_"

SUFFIX_ACE = "ACE"
SUFFIX_VET = "VET"
SUFFIX = "TRN"


