---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yauta.
--- DateTime: 13.10.2022 08:19
---
ZONE_RED_BORDER_1 = ZONE_POLYGON:NewFromGroupName("RED_BORDER_1")
ZONE_RED_BORDER_2 = ZONE_POLYGON:NewFromGroupName("RED_BORDER_2")
ZONE_RED_CONFLICT = ZONE_POLYGON:NewFromGroupName("RED_CONFLICT_1")

ZONE_RED_AAR = ZONE:New("RED_AAR")
ZONE_RED_AWACS = ZONE:New("RED_AWACS")
ZONE_RED_PATROL_1 = ZONE:New("RED_PATROL_1")
ZONE_RED_PATROL_2 = ZONE:New("RED_PATROL_2")

-- ###########################################################
-- ###                      RED CHIEF                      ###
-- ###########################################################

RedAgentSet = SET_GROUP:New():FilterCoalitions("red"):FilterStart()

RedBorderZoneSet = SET_ZONE:New()
RedBorderZoneSet:AddZone(ZONE_RED_BORDER_1)
RedBorderZoneSet:AddZone(ZONE_RED_BORDER_2)

ConflictZoneSet = SET_ZONE:New()
ConflictZoneSet:AddZone(ZONE_RED_CONFLICT)

RedChief = CHIEF:New("red", RedAgentSet, "Comrade RedChief")
RedChief:SetBorderZones(RedBorderZoneSet)
RedChief:SetConflictZones(ConflictZoneSet)
RedChief:SetStrategy(CHIEF.Strategy.DEFENSIVE)
-- LIMITS

AW_Assad = AIRWING:New("Static Warehouse-4-1", "Assad Air Wing")

AW_Assad:SetMarker(false)
AW_Assad:SetAirbase(AIRBASE:FindByName(AIRBASE.Syria.Bassel_Al_Assad))
AW_Assad:SetRespawnAfterDestroyed(600)
AW_Assad:__Start(2)

AW_Assad_MiG_21 = SQUADRON:New("Red Mig21 CAP", 12, "Red Mig21 CAP")
AW_Assad_MiG_21:SetGrouping(1)
AW_Assad_MiG_21:SetSkill(AI.Skill.EXCELLENT)
AW_Assad_MiG_21:SetTakeoffType("Hot")
AW_Assad_MiG_21:AddMissionCapability({ AUFTRAG.Type.CAP, AUFTRAG.Type.INTERCEPT }, 100)
AW_Assad_MiG_21:SetFuelLowRefuel(false)
AW_Assad_MiG_21:SetFuelLowThreshold(0.4)
AW_Assad:AddSquadron(AW_Assad_MiG_21)
AW_Assad:NewPayload("Red Mig21 CAP", 2, { AUFTRAG.Type.CAP }, 50)
AW_Assad:NewPayload("Red Mig21 CAP", 1, { AUFTRAG.Type.INTERCEPT }, 90)


AW_Assad_MiG_23 = SQUADRON:New("Red Mig23 Intercept", 6, "Red Mig23 Intercept")
AW_Assad_MiG_23:SetGrouping(1)
AW_Assad_MiG_23:SetSkill(AI.Skill.EXCELLENT)
AW_Assad_MiG_23:SetTakeoffType("Hot")
AW_Assad_MiG_23:AddMissionCapability({ AUFTRAG.Type.CAP, AUFTRAG.Type.INTERCEPT }, 100)
AW_Assad_MiG_23:SetFuelLowRefuel(false)
AW_Assad_MiG_23:SetFuelLowThreshold(0.4)
AW_Assad:AddSquadron(AW_Assad_MiG_23)
AW_Assad:NewPayload("Red Mig23 Intercept", 2, { AUFTRAG.Type.INTERCEPT }, 100)

AW_Assad_MiG_29 = SQUADRON:New("Red Mig29 BVR", 4, "Red Mig29 BVR")
AW_Assad_MiG_29:SetGrouping(2)
AW_Assad_MiG_29:SetSkill(AI.Skill.EXCELLENT)
AW_Assad_MiG_29:SetTakeoffType("Hot")
AW_Assad_MiG_29:AddMissionCapability({ AUFTRAG.Type.CAP }, 100)
AW_Assad_MiG_29:SetFuelLowRefuel(false)
AW_Assad_MiG_29:SetFuelLowThreshold(0.4)
AW_Assad:AddSquadron(AW_Assad_MiG_29)
AW_Assad:NewPayload("Red Mig29 BVR", 2, { AUFTRAG.Type.CAP }, 100)


AW_Assad_Su_33 = SQUADRON:New("Red Su33 BVR", 4, "Red Su33 BVR")
AW_Assad_Su_33:SetGrouping(2)
AW_Assad_Su_33:SetSkill(AI.Skill.EXCELLENT)
AW_Assad_Su_33:SetTakeoffType("Hot")
AW_Assad_Su_33:AddMissionCapability({ AUFTRAG.Type.CAP, AUFTRAG.Type.ESCORT, AUFTRAG.Type.INTERCEPT }, 100)
AW_Assad_Su_33:SetFuelLowRefuel(true)
AW_Assad_Su_33:SetFuelLowThreshold(0.4)
AW_Assad:AddSquadron(AW_Assad_Su_33)

AW_Assad:NewPayload("Red Su33 BVR", 2, { AUFTRAG.Type.CAP, AUFTRAG.Type.ESCORT, AUFTRAG.Type.PATROLZONE }, 100)
AW_Assad:NewPayload("Red Su33 BVR", 1, { AUFTRAG.Type.INTERCEPT }, 70)

AW_Assad_AAR = SQUADRON:New("Red AAR", 3, "Red AAR Squadron")
AW_Assad_AAR:AddMissionCapability({ AUFTRAG.Type.TANKER }, 100)
AW_Assad_AAR:SetSkill(AI.Skill.EXCELLENT)
AW_Assad_AAR:SetTakeoffType("Hot")
AW_Assad_AAR:SetFuelLowRefuel(false)
AW_Assad_AAR:SetFuelLowThreshold(0.3)
AW_Assad_AAR:SetTurnoverTime(30, 5)
AW_Assad:AddSquadron(AW_Assad_AAR)
AW_Assad:NewPayload("Red AAR", -1, { AUFTRAG.Type.TANKER }, 100)

AW_Assad_AWACS = SQUADRON:New("Red AWACS", 2, "Red AWACS Squadron")
AW_Assad_AWACS:AddMissionCapability({ AUFTRAG.Type.AWACS }, 100)
AW_Assad_AWACS:SetTakeoffType("Hot")
AW_Assad_AWACS:SetFuelLowRefuel(true)
AW_Assad_AWACS:SetFuelLowThreshold(0.4)
AW_Assad_AWACS:SetTurnoverTime(30, 5)
AW_Assad_AWACS:SetRadio(251)
AW_Assad:AddSquadron(AW_Assad_AWACS)
AW_Assad:NewPayload("Red AWACS", -1, { AUFTRAG.Type.AWACS }, 100)

RedChief:SetLimitMission(1, AUFTRAG.Type.TANKER)
RedChief:SetLimitMission(1, AUFTRAG.Type.AWACS)
RedChief:SetLimitMission(1, AUFTRAG.Type.INTERCEPT)
RedChief:SetLimitMission(1, AUFTRAG.Type.CAP)

-- RESOURCES
RedChief:AddAirwing(AW_Assad)
RedChief:AddCapZone(ZONE_RED_PATROL_1, 25000, 275, 025, 20)
RedChief:AddCapZone(ZONE_RED_PATROL_2, 20000, 275, 180, 20)
RedChief:AddAwacsZone(ZONE_RED_AWACS, 33000, 450, 0, 25)
RedChief:AddTankerZone(ZONE_RED_AAR, 25000, 340, 0, 30, 1)
RedChief:AddTankerZone(ZONE_RED_AAR, 25000, 340, 0, 30, 1)
RedChief:__Start(2)