Spawn_Shell_One= SPAWN:New("SPAWN SH1"):InitLimit( 1, 0 ):SpawnScheduled( 60, .1 ):InitRepeatOnLanding()
Spawn_Shell_Two = SPAWN:New("SPAWN SH2"):InitLimit( 1, 0 ):SpawnScheduled( 60, .1 ):InitRepeatOnLanding()
Spawn_Texaco_One = SPAWN:New("SPAWN TX1"):InitLimit( 1, 0 ):SpawnScheduled( 60, .1 ):InitRepeatOnLanding()
Spawn_Focus_One = SPAWN:New("SPAWN FC1"):InitLimit( 1, 0 ):SpawnScheduled( 60, .1 ):InitRepeatOnLanding()
Spawn_Focus_Two = SPAWN:New("SPAWN FC2"):InitLimit( 1, 0 ):SpawnScheduled( 60, .1 ):InitRepeatOnLanding()