AtisHatay = ATIS:New(AIRBASE.Syria.Ramat_David, FREQUENCIES.GROUND.atis_ramat_david_vhf[1])
AtisHatay:SetRadioRelayUnitName("Ramat Relay")
AtisHatay:SetTowerFrequencies({FREQUENCIES.GROUND.tower_ramat_david_uhf[1], FREQUENCIES.GROUND.tower_ramat_david_vhf[1]})
AtisHatay:AddILS(111.10, "33")
AtisHatay:AddNDBinner(368.00)
AtisHatay:SetVOR(113.70)
AtisHatay:SetSRS(SRS_PATH, "female", "en-US")
AtisHatay:SetMapMarks()
AtisHatay:Start()
