zones_civil = {
    ZONE:New("CIVIL ZONE 14"),
    ZONE:New("CIVIL ZONE 13"),
    ZONE:New("CIVIL ZONE 12"),
    ZONE:New("CIVIL ZONE 11"),
    ZONE:New("CIVIL ZONE 10"),
    ZONE:New("CIVIL ZONE 9"),
    ZONE:New("CIVIL ZONE 8"),
    ZONE:New("CIVIL ZONE 7"),
    ZONE:New("CIVIL ZONE 6"),
    ZONE:New("CIVIL ZONE 5"),
    ZONE:New("CIVIL ZONE 4"),
    ZONE:New("CIVIL ZONE 3"),
    ZONE:New("CIVIL ZONE 2"),
    ZONE:New("CIVIL ZONE 1"),
}
