-- placeholder
rat_c47=RAT:New("rat_1")
rat_a26=RAT:New("rat_2")
rat_fwa=RAT:New("rat_3")
rat_fwd=RAT:New("rat_4")
rat_c47:SetDeparture({AIRBASE.Caucasus.Senaki_Kolkhi, AIRBASE.Caucasus.Kutaisi})
rat_c47:SetDestination({AIRBASE.Caucasus.Senaki_Kolkhi, AIRBASE.Caucasus.Kutaisi})
rat_a26:SetDeparture({AIRBASE.Caucasus.Senaki_Kolkhi, AIRBASE.Caucasus.Kutaisi})
rat_a26:SetDestination({AIRBASE.Caucasus.Senaki_Kolkhi, AIRBASE.Caucasus.Kutaisi})
rat_fwa:SetDeparture({AIRBASE.Caucasus.Senaki_Kolkhi, AIRBASE.Caucasus.Kutaisi})
rat_fwa:SetDestination({AIRBASE.Caucasus.Senaki_Kolkhi, AIRBASE.Caucasus.Kutaisi})
rat_fwd:SetDeparture({AIRBASE.Caucasus.Senaki_Kolkhi, AIRBASE.Caucasus.Kutaisi})
rat_fwd:SetDestination({AIRBASE.Caucasus.Senaki_Kolkhi, AIRBASE.Caucasus.Kutaisi})
rat_c47:Spawn(1)
rat_a26:Spawn(1)
rat_fwa:Spawn(1)
rat_fwd:Spawn(1)