import os

PATH_MISSION_SCRIPTS = os.path.dirname(os.path.abspath(__file__))
PATH_SCRIPT_VARIABLES = os.path.join(PATH_MISSION_SCRIPTS, "1_1_variables.lua")
PATH_SCRIPT_COMMON = os.path.join(PATH_MISSION_SCRIPTS, "1_2_common.lua")
PATH_SCRIPT_RADIO_PRESETS = os.path.join(PATH_MISSION_SCRIPTS, "2_1_radio_presets.lua")
PATH_SCRIPT_MENU = os.path.join(PATH_MISSION_SCRIPTS, "3_1_menu.lua")
PATH_SCRIPT_ATIS = os.path.join(PATH_MISSION_SCRIPTS, "3_2_atis.lua")
PATH_SCRIPT_ELINT = os.path.join(PATH_MISSION_SCRIPTS, "4_1_3_elint.lua")
PATH_SCRIPT_CSAR = os.path.join(PATH_MISSION_SCRIPTS, "4_1_5_csar.lua")
PATH_SCRIPT_FOX_TRAINER = os.path.join(PATH_MISSION_SCRIPTS, "4_1_6_fox_trainer.lua")
PATH_SCRIPT_TRAINING_GROUND_AG = os.path.join(PATH_MISSION_SCRIPTS, "4_1_7_training_ground_ag.lua")
PATH_SCRIPT_REDCHIEF = os.path.join(PATH_MISSION_SCRIPTS, "4_2_2_redchief.lua")
PATH_SCRIPT_SCHEDULERS = os.path.join(PATH_MISSION_SCRIPTS, "5_1_1_schedulers.lua")
PATH_SCRIPT_AW_KUTAISI = os.path.join(PATH_MISSION_SCRIPTS, "AW_Kutaisi.lua")
PATH_SCRIPT_AW_MOZDOK = os.path.join(PATH_MISSION_SCRIPTS, "AW_Mozdok.lua")
PATH_SCRIPT_AW_VAZIANI = os.path.join(PATH_MISSION_SCRIPTS, "AW_Vaziani.lua")
PATH_SCRIPT_PATHS = os.path.join(PATH_MISSION_SCRIPTS, "paths.lua")
