SECONDS_PER_DAY = 86400
SECONDS_PER_HALF_DAY = 43200

MosieNavigator = MosieNavigator or {}

MosieNavigator.Config = MosieNavigator.Config or {
  flightZonePrefix = "MN_",
  beaconZonePrefix = "MNB_",
  coalition = -1,
  readOnly = true,
  waypointLineAlpha = 0.95,
  waypointFillAlpha = 0.25,
  beaconLineAlpha = 0.85,
  beaconFillAlpha = 0.22,
  defaultBeaconPowerNm = 60,
  defaultBeaconAltitudeFt = 0,
  defaultWaypointRadiusM = 250,
  generateFlightPlanFiles = true,
  generateCsvFiles = true,
  flightPlanOutputDirectory = nil,
  groupPlanTagPattern = "%[MN:([%w%-]+)%]",
  menuName = "Mosie Navigator",
  flightPlanMessageDuration = 30,
  menuRefreshDelay = 5,
  menuRefreshInterval = 15,
  navigatorTickInterval = 5,
  navigatorReportIntervalDefault = 120,
  navigatorReportIntervals = {30, 60, 120, 300},
  navigatorMessageDuration = 20,
  navigatorCalloutSeconds = {60, 30},
  navigatorXteStepNm = 1,
}

MosieNavigator.WaypointTypes = {
  TAKE_OFF = true,
  LANDING = true,
  INGRESS = true,
  TARGET = true,
  EGRESS = true,
  NAV = true,
  HOLD = true,
}

MosieNavigator.PlanColors = {
  {0.20, 0.60, 1.00},
  {1.00, 0.55, 0.10},
  {0.30, 0.90, 0.35},
  {0.90, 0.30, 0.90},
  {1.00, 0.90, 0.20},
  {0.15, 0.90, 0.90},
  {1.00, 0.25, 0.25},
}

MosieNavigator.BeaconColor = {0.20, 0.80, 0.20}

MosieNavigator.Aircraft = MosieNavigator.Aircraft or {
  name = "Mosquito FB Mk VI",
  defaultCruiseSpeedMph = 228,
  defaultCruiseSpeedKt = 228 * 0.8689762419,
  engineSettings = {
    {
      id = "takeoff_emergency_18",
      name = "Take-Off / Emergency +18",
      rpm = 3000,
      mixture = "rich",
      boostPsi = 18,
      limitMin = 5,
      fuelImpGphPerEngine = nil,
      fuelImpGph = nil,
      seaLevelIasKt = nil,
      notes = "+18 may not be used below 2850 RPM",
    },
    {
      id = "takeoff_12",
      name = "Take-Off +12",
      rpm = 3000,
      mixture = "rich",
      boostPsi = 12,
      fuelImpGphPerEngine = 115,
      fuelImpGph = 230,
      seaLevelIasKt = nil,
    },
    {
      id = "max_climb",
      name = "Max Climbing Power",
      rpm = 2850,
      mixture = "rich",
      boostPsi = 9,
      limitMin = 60,
      fuelImpGphPerEngine = 95,
      fuelImpGph = 190,
      seaLevelIasMph = 240,
      tenThousandFtIasMph = 240,
      seaLevelIasKt = 240 * 0.8689762419,
      profileName = "climb",
      profileCode = "CLB",
    },
    {
      id = "max_cont_rich",
      name = "Max Continuous Rich",
      rpm = 2650,
      mixture = "rich",
      boostPsi = 7,
      fuelImpGphPerEngine = 80,
      fuelImpGph = 160,
      seaLevelIasMph = 237,
      tenThousandFtIasMph = 237,
      seaLevelIasKt = 237 * 0.8689762419,
      profileName = "cont_r",
      profileCode = "MCR",
    },
    {
      id = "max_cont_weak",
      name = "Max Continuous Weak",
      rpm = 2650,
      mixture = "weak",
      boostPsi = 7,
      fuelImpGphPerEngine = 63,
      fuelImpGph = 126,
      seaLevelIasMph = 228,
      tenThousandFtIasMph = 226,
      seaLevelIasKt = 228 * 0.8689762419,
      profileName = "cont_w",
      profileCode = "MCW",
    },
    {
      id = "cruise_weak",
      name = "Cruise Weak",
      rpm = 2300,
      mixture = "weak",
      boostPsi = 2,
      fuelImpGphPerEngine = 42,
      fuelImpGph = 84,
      seaLevelIasMph = 192,
      tenThousandFtIasMph = 198,
      seaLevelIasKt = 192 * 0.8689762419,
      profileName = "cruise",
      profileCode = "CRZ",
    },
  },
  fuelCurveSettingIds = {
    "cruise_weak",
    "max_cont_weak",
    "max_cont_rich",
    "max_climb",
  },
  envelope = {
    minIasKt = 165,
    maxIasMph = 245,
    maxIasKt = 245 * 0.8689762419,
  },
  fuel = {
    unit           = "IMP_GAL",
    tankCapacity   = 653.1,
    internalFuelLb = 3269,
    fuelLbPerGal   = 7.215,
    internalFuelBufferPercent = 1,
    dropTankOptions = {
      { label = "NONE", gal = 0 },
      { label = "2x50 GAL", gal = 100 },
      { label = "2x100 GAL", gal = 200 },
    },
    taxiAllowance  = 15,
    landingAllowance = 5,
    reserveMinutes = 30,
  },
  holdIasKt      = 140,
  holdBurnImpGph = 84,
}
